name: Thompson
favicon: null
layout_spectrum: 0.40671
typography_spectrum: 0.97659
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#766f7f'
    - '#2d2e28'
    - '#c4a69c'
    - '#aa7f20'
    - '#843a05'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.6875
  rhythmicContrast: 0.75
purpose: []
